services:
  - type: pserv
    name: postgres
    env: postgres
    postgres:
      version: 15

  - type: web
    name: backend
    env: python
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    repo: https://github.com/XkhldY/recruiting.git # CHANGE THIS
    branch: master # CHANGE THIS
    healthCheckPath: /api
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: postgres
          property: connectionString

  - type: web
    name: frontend
    env: node
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    repo: https://github.com/XkhldY/recruiting.git # CHANGE THIS
    branch: master # CHANGE THIS
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
