# render.yaml

databases:
  - name: recruiting-db
    databaseName: recruiting_db
    user: recruiting_user
    plan: free

services:
  # Backend Web Service (FastAPI)
  - type: web
    name: backend-service
    env: python
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api
    instanceType: starter # Explicitly set to free tier instance type
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recruiting-db
          property: connectionString

  # Frontend Web Service (React)
  - type: web
    name: frontend-service
    env: node
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    instanceType: starter # Explicitly set to free tier instance type
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend-service-recruiting.onrender.com # Public URL for frontend to access backend
