name: CI/CD Pipeline

on:
  push:
    branches:
      - wed
  pull_request:
    branches:
      - wed

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: pip install -r requirements.txt pytest
        working-directory: ./backend

      - name: Run backend tests
        run: pytest
        working-directory: ./backend
